before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "sapher/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "sapher/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .CommitTimestamp }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "sapher/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "sapher/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .CommitTimestamp }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
docker_manifests:
  - name_template: "sapher/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "sapher/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "sapher/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "sapher/{{ .ProjectName }}:latest"
    image_templates:
      - "sapher/{{ .ProjectName }}:latest-amd64"
      - "sapher/{{ .ProjectName }}:latest-arm64"
changelog:
  skip: true
