repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.0
    hooks:
      - id: golangci-lint
        name: Lint Golang code
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-jsonschema
        name: Check JSON rules
        files: ^(pkg/linter/rules.json)
        args:
          - --schemafile
          - pkg/linter/rules.schema.json
  - repo: local
    hooks:
      - id: generate-rules-table
        name: Generate rules table
        entry: ./hooks/generate_rules_table.sh
        language: script
        files: ^(pkg/linter/rules.json|README.md)
        args:
          - "pkg/linter/rules.json"
          - "README.md"
